### PR TITLE
Grant/readme

### PR DESCRIPTION
**Pull request by GrantCT**

### CODE REVIEW

**Comment by a-hend** [comment]
Grant, your changes to the readme are not specific.  Please try again

**Review by missmshel — APPROVED** [review]
Acceptable

**Review by missmshel — APPROVED** [review]
Acceptable

**Review by a-hend — CHANGES_REQUESTED** [review]
Grant, great try man!  Do better next time :-)

**Review by nguyentomt — APPROVED** [review]
Looks adequate

**Review by a-hend — APPROVED** [review]
JK

**Review by missmshel — APPROVED** [review]

**Review by missmshel — APPROVED** [review]

**Review by a-hend — APPROVED** [review]

**Review by jl3z — APPROVED** [review]

**Pull request merged**
